apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-poc
  labels:
    app: worker-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-poc
  template:
    metadata:
      name: worker-poc
      labels:
        app: worker-poc
    spec:
      restartPolicy: Always
      containers:
        - name: worker
          image: runtime-poc-worker:latest
          imagePullPolicy: Never
      initContainers:
        - name: worker-agent
          image: runtime-poc-agent:latest
          imagePullPolicy: Never
          restartPolicy: Always
          ports:
            - containerPort: 8888
              protocol: TCP